### ISSUE TITLE
Serves text/event-stream format  phystrix  timeout 2min

### ISSUE THREAD

**Issue by yangqinjiang** [upwork/phystrix-dashboard#3]
![image](https://user-images.githubusercontent.com/1914373/31763050-a16d9b9a-b4ef-11e7-8185-add92dc4090e.png)

What's happen??

Env:
apache ,
php5.5

**Comment by yangqinjiang** [comment]
what's  happy??

**Comment by lcf** [comment]
@yangqinjiang the endpoint is a data stream, that is expected. Did I understand your concern correctly?
